/**
 * Combined chord database barrel
 * Merges the main chord library with extended chord families
 */
import { CHORD_DATABASE as BASE_CHORDS } from './chords';
import {
  AUG7SHARP9_E6_MOVABLE,
  AUG7SHARP9_A5_MOVABLE,
  DOM7SHARP9_E6_BARRE,
  MAJ7SHARP11_E6_MOVABLE,
  MAJ7SHARP11_A5_BARRE,
  DOM7SHARP9_A5_MOVABLE_V2,
  AUG7B9_E6_MOVABLE,
  AUG7B9_A5_MOVABLE,
  DOM7B9_E6_MOVABLE,
  DOM7B9_A5_MOVABLE,
  MINMAJ7_E6_BARRE,
  MINMAJ7_A5_BARRE,
  MINOR6_A5_MOVABLE,
  MAJOR6_A5_BARRE,
  AUG7_E6_MOVABLE,
  AUG7_A5_MOVABLE,
} from './chords-extended';

export const CHORD_DATABASE = [
  ...BASE_CHORDS,
  ...AUG7SHARP9_E6_MOVABLE,
  ...AUG7SHARP9_A5_MOVABLE,
  ...DOM7SHARP9_E6_BARRE,
  ...MAJ7SHARP11_E6_MOVABLE,
  ...MAJ7SHARP11_A5_BARRE,
  ...DOM7SHARP9_A5_MOVABLE_V2,
  ...AUG7B9_E6_MOVABLE,
  ...AUG7B9_A5_MOVABLE,
  ...DOM7B9_E6_MOVABLE,
  ...DOM7B9_A5_MOVABLE,
  ...MINMAJ7_E6_BARRE,
  ...MINMAJ7_A5_BARRE,
  ...MINOR6_A5_MOVABLE,
  ...MAJOR6_A5_BARRE,
  ...AUG7_E6_MOVABLE,
  ...AUG7_A5_MOVABLE,
];
